### ISSUE TITLE
Failed Queries

### ISSUE THREAD

**Issue by steveoh** [agrc/daq-web-framework#10]
Failed queries do not toast a message. Handle the sad path.

**Comment by woswald** [comment]
@steveoh 
Should this be providing an error message if a query returns 0 results or fails?  If this is the case, it does not appear to be working.

If I attempt the following query, I get no error message: 
Layer: Failities_inprogress 
Query: Ai Number
Input: 2

I just get what seems like nothing happening.

**Comment by steveoh** [comment]
It currently is not but it can be.

**Comment by woswald** [comment]
When I tried to test this I discovered that the query tool no longer seems to be working.

**Steps to Reproduce**
1) Navigate to http://test.mapserv.utah.gov/daq/
2) After page loads, click on the query tool at the bottom of the map.
3) In the query tool select the following:
Layer: Permits (as of Nov. 1, 2016)
Query: Ai Number
Input: 12514
4) Click the Query button. Nothing seems to happen, no point gets highlighted, and no error is received.
5) In pictures below you can see verification that there should be a result returned for the query for Ai number: 12514.

![image](https://cloud.githubusercontent.com/assets/7386943/23516993/2e50f2b6-ff2c-11e6-890c-540e69d6d0c2.png)

**Comment by steveoh** [comment]
Ok.

![image](https://cloud.githubusercontent.com/assets/325813/23517129/b2c86dd0-ff2c-11e6-854c-a37c93f89cbf.png)
