### ISSUE TITLE
Edit AI #

### ISSUE THREAD

**Issue by steveoh** [agrc/daq-web-framework#11]
AI Numbers need to be editable after they are set.

**Comment by woswald** [comment]
Also can we make room for more than one AI#.  I think in some instances a facility can have more than one AI#.

**Comment by steveoh** [comment]
I don't understand how this could work if it's a field in a table and not a related item. Are we going to add multiple to the single text box with commas or something?

**Comment by woswald** [comment]
I am not certain about this either, maybe we can discuss more at our next meeting. If it isn't possible we'll forget about it.

**Comment by steveoh** [comment]
we decided to keep just one ai number at a time

**Comment by woswald** [comment]
I am not able to see where any of the AI#'s are now editable. It does not appear that I can click on them or anything through the Item Information window.

**Comment by steveoh** [comment]
![image](https://cloud.githubusercontent.com/assets/325813/24002347/1e0a6f72-0a26-11e7-8c77-9c737d3fefc5.png)

There's a button to edit the AI. Make sure your version at the top says 1.5.0

**Comment by woswald** [comment]
Steps to reproduce:
Click on a facilities point which has an existing AI#.
On the Feature Information tab in the Item Information window, click the "Update AI#" button.
Ener a new five-digit AI# such as 10791. Click the "Add AI Number" button.
The window automatically goes to the EDoc Items tab.
Click on the Feature Information tab.
Although an AI# has been entered and accepted, as it now appears in in te AI# field.  The "AI Numbers are required! Please locate the AI number for this item." error is displayed. 
Additionally, the entered 5 digit AI#, now persists in the Add AI number entry field.
![image](https://cloud.githubusercontent.com/assets/7386943/24003082/1c4f3ecc-0a28-11e7-9892-cabc9d242ede.png)

What should occur:
Click on a facilities point which has an existing AI#.
On the Feature Information tab in the Item Information window, click the "Update AI#" button.
Ener a new five-digit AI# such as 10791. Click the "Add AI Number" button.
The window automatically goes to the EDoc Items tab.
Click on the Feature Information tab.
They newly entered AI# should now appear in the AI# field.
As long as the 5 digit AI# was correctly entered, no entry fields or error should now be shown.

**Comment by steveoh** [comment]
I created https://github.com/agrc/daq-web-framework/issues/36 for this issue.
