### ISSUE TITLE
Unable to Use/View Web App on Tablet

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#16]
### Steps to reproduce
1. Open Chrome browser on android tablet.
2.  Enter: http://test.mapserv.utah.gov/daq/
3. log into umd
4. receive blank screen (see screenshot)

### Expected behaviour
Should be able to view the webmap hosted in the app at http://test.mapserv.utah.gov/daq/

### Actual behaviour
After logging into UMD, I just get a blank screen no webmap is visible

### Client configuration
**Browser:**
Chrome 52.0.2743.98
**Operating system:**
Android 5.1.1; Samsung Galaxy Note 10.1 SM-P605V Build/LMY47X

![screenshot_2017-02-02-14-04-23](https://cloud.githubusercontent.com/assets/7386943/22568420/0c13d70e-e951-11e6-9a56-816a4499a8c5.png)

**Comment by steveoh** [comment]
please open the dev tools in chrome, right click, click inspect, then right click in the console area and click save as. Email me the log so I can look into this. I will try the UDWN network on monday.

**Comment by steveoh** [comment]
We were missing some dynamically required touch event files. After those were included there was still some "strange" behavior. We need to test this out in our office on an android tablet. @brigsz do we still have one of those or will I need to bring my personal one?

**Comment by steveoh** [comment]
This should be working now.
