### ISSUE TITLE
Document Expiration - 30 Days

### ISSUE THREAD

**Issue by brigsz** [agrc/daq-web-framework#18]
lets keep document attachments and image attachments for 30 days, and then automatically delete then from AGOL. This gives them enough time to get around to viewing them and writing their memo.

**Comment by steveoh** [comment]
Will we need to differentiate between application uploaded items and static assets? Wasn't there chatter about keeping certain files indefinitely?

this will have to be taken care of with #7 by adding the attachment date to the filename.

**Comment by steveoh** [comment]
@woswald or @brigsz what about the indefinite files?

**Comment by woswald** [comment]
After discussion with inspectors, I don't think we need any indefinite files.  30 days should give them plenty of time to use the attached files.  Any important notes can be added to the notes field, and those will remain indefinitely.

**Comment by steveoh** [comment]
@woswald is this only necessary for the `Facilities` Feature Service or is there a reason to need more than that?

**Comment by woswald** [comment]
It should just be for the Facilities feature service, it is currently the only one that accepts attachments.

**Comment by steveoh** [comment]
@woswald what do you want to do with files that aren't uploaded via the app? Skip them or auto delete them?

**Comment by woswald** [comment]
@steveoh Auto delete them.
