### ISSUE TITLE
TRS Search

### ISSUE THREAD

**Issue by brigsz** [agrc/daq-web-framework#19]
Need functionality to Search by section, township, and range.

**Comment by steveoh** [comment]
Is the goal to zoom to a location or to populate a grid with all of the items in a certain section or both?

**Comment by steveoh** [comment]
@woswald or @brigsz would you mind responding to my question?

**Comment by woswald** [comment]
I think that zooming to a location would be sufficient.

**Comment by woswald** [comment]
Request: 
Would it be possible to add a temporary grid box around the specific section/township/range that was searched for?  This would allow the user to search for a specific section/township/range but then be able to zoom out a bit to get an idea of the surrounding areas, but still being able to see which section/township/range was identified.  This tempory grid box could just go away once the s/t/r tool is closed, or another s/t/r is searched for.

**Comment by steveoh** [comment]
I created https://github.com/agrc/daq-web-framework/issues/39 to track that request
