### ISSUE TITLE
Split between Viewers

### ISSUE THREAD

**Issue by brigsz** [agrc/daq-web-framework#20]
When you click on a point and the attribute viewer appears, can we adjust the split between the attribute viewer and the document viewer (see attached doc)?  The general consensus of the inspectors was that they didn't want to have to scroll as much on that screen to see the item information.

**Comment by steveoh** [comment]
So more space for the attributes and less space for the table?

**Comment by steveoh** [comment]
@woswald or @brigsz please respond?

**Comment by woswald** [comment]
Yes, more space for the attributes and less for the table.

**Comment by woswald** [comment]
Is is possible to have dynamic split, so that the user could drag the split line up or down according to their preference?

**Comment by steveoh** [comment]
Maybe we should add a tab for the attributes and the table if those two items are fighting for space

**Comment by woswald** [comment]
I think that is a great idea.
