### ISSUE TITLE
Expanded Queries

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#24]
Can we made the following highlighted fields searchable by query?

[ComplianceMap-IncludedLayers.xlsx](https://github.com/agrc/daq-web-framework/files/772018/ComplianceMap-IncludedLayers.xlsx)

![image](https://cloud.githubusercontent.com/assets/325813/22907472/8ae84246-f206-11e6-84fd-2b3d056fb10b.png)

**Comment by steveoh** [comment]
Everything in yellow should be in the canned queries area except lat/long

**Comment by steveoh** [comment]
@woswald 

`2015 O&G Wells` does not have an `API #`, `Operator Name`, or `Well Type` field from what I can tell. Please tell me the feature class field name from [this service](https://services2.arcgis.com/NnxP4LZ3zX8wWmP9/arcgis/rest/services/2015_OilandGasWells/FeatureServer/0)

`2014 O&G Facilities` does not have a `Permit Number` or `Jurisdiction` field from what I can tell. Please tell me the field name from [this service](https://services2.arcgis.com/NnxP4LZ3zX8wWmP9/arcgis/rest/services/2015_OGFacilities/FeatureServer/0/)

`TempoPermits` does not have a `Facility Name`, `AI #`, and is `Permit_ID` the `Permit Number`? Please tell me the field names from [this service](https://services2.arcgis.com/NnxP4LZ3zX8wWmP9/arcgis/rest/services/2015_OGPermits_20161101/FeatureServer/0)

**Comment by woswald** [comment]
@steveoh 
Is this what you are looking for?

2015 O&G Wells: 
Alias: "API #" Non-alias: "F2015_DOGM_"
Alias: "Operator Name" Non-alias: "CO_NAME"
Alias: "Well Type" Non-alias: "Assigned_T"

2014 O&G Facilities:
Alias: "Permit Number" Non-alias: "facility_p"
Alias: "Jurisdiction" Non-alias: "facility_j"

TempoPermits:
Alias: "Facility Name" Non-alias: "Site_Name"
Alias: "AI #" Non-alias: "SITE_ID"
Alias: "Permit #" Non-alias: "Permit_ID"

**Comment by steveoh** [comment]
@woswald yes, could you verify I didn't make any mistakes.

```js
            well: {
                wellName: 'WELL_NAME',
                apiNumber: 'F2015_DOGM_',
                operatorName: 'CO_NAME',
                wellType: 'Assigned_T',
                jurisdiction: 'Juris'
            },
            facility: {
                facilityName: 'facility_n',
                operatorName: 'Operator_N',
                permitNumber: 'facility_p',
                aiNumber: 'AI_Number',
                jurisdiction: 'facility_j',
                inspector: 'Inspector'
            },
            permit: {
                facilityName: 'Site_Name',
                aiNumber: 'SITE_ID',
                permitNumber: 'Permit_ID'
            }
```

**Comment by woswald** [comment]
@steveoh 
Looks correct to me.

**Comment by woswald** [comment]
@steveoh 

Some of the queries that return a large number of results don't appear to be working properly (see image).

This is the case with the layer 2015_OilandGasWells and both the Jurisdiction and Well Type queries. 

If this ends up being something that we can't fix, we should just remove these two queries.

**Comment by steveoh** [comment]
What image is that?

**Comment by steveoh** [comment]
@woswald please let me know what queries you are running with what values so I can reproduce please.

**Comment by woswald** [comment]
@steveoh 

Sorry I couldn't get the image to attach yesterday.  I am running a queries on the layer "2015_OilandGasWells" one query is "Jurisdiction" I have used State, Indian Country, or Reservation and Tribal Land as the input, the issues seem to happen with all of them.  Another query on the same layer is "Well Type", I have used OW and GW as the input, the issue seems to happen with them both.

Here is an example image (other layer turned off for easier viewing):
![image](https://cloud.githubusercontent.com/assets/7386943/23468252/90ae1670-fe5d-11e6-922e-95282f54b2b3.png)

and 
![image](https://cloud.githubusercontent.com/assets/7386943/23468441/0ea06fec-fe5e-11e6-9e79-eefcb31aa123.png)

**Comment by steveoh** [comment]
the issue being that all more of the points aren't selected?

I will verify that these are the correct outcomes and figure out why some are missing.
![image](https://cloud.githubusercontent.com/assets/325813/23469615/49097022-fe61-11e6-85ac-b34405b4d3bd.png)

**Comment by steveoh** [comment]
The problem is the max record count. It is limited to 1000 and that is the total number of points being returned from the service. I think you can tweak this number but it comes at a cost. Would you like me to remove all of the queries with more than 1000 records?

**Comment by woswald** [comment]
@steveoh Any idea what the associated costs might be?

**Comment by steveoh** [comment]
Mainly performance costs. Requests will take longer, draw times will be slower, you'll have increased demand on the device rendering so it can slow down panning, zooming, and your entire computer/device. If it was hosted on your arcgis server infrastructure then it would put more stress on it's resources but these are hosted feature services if I remember correctly.

**Comment by woswald** [comment]
I am inclined to just get rid of queries with >1000 records.  However, I would like to make sure I am getting rid of any really important query. Is there any easy way to get a list of the which queries would run into this limit?  Maybe the best way to handle it would be to throw out nay queries that will always run into more than 1000 records being returned.  And for others where it would only happen sometimes, maybe only when the correct input is provided, just throw an error that says the returned records limit has been exceeded, or something like that.  Thoughts?

**Comment by steveoh** [comment]
If you look at the properties of each field it will tell you the statistics for all entries. You WI se that table I posted above.

**Comment by steveoh** [comment]
You have to look in arcgis online or you could use arc map

**Comment by woswald** [comment]
Let's get rid of any of the "jurisdiction" and "well type" queries. And then just use the message pop up for others that exceed 1000, like "operator name".

**Comment by woswald** [comment]
Request:
Would it be possible to add geographic subqueries to the queries?

Current Behavior:
1. Let the map load.
2. Click on the query tool icon at the bottom of the screen.
3. Select Layer to Query.
4. Select Query.
5. Enter Input.
6. Points that match query criteria are returned with highlight.

Desired Behavior:
1. Let the map load.
2. Click on the query tool icon at the bottom of the screen.
3. Select Layer to Query.
4. Select Query.
5. Select a geographic area to apply query to: this could use a drop down with county names, or statewide, or maybe drawable shape.
6. Enter Input.
7. Points that match query criteria are returned with highlight.

**Comment by steveoh** [comment]
i made https://github.com/agrc/daq-web-framework/issues/40 to track that feature.
