### ISSUE TITLE
Buffer Tool

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#29]
This tool appears to not be working now.

**Comment by steveoh** [comment]
@woswald please do not omit the description of what not working is.

**Comment by woswald** [comment]
@steveoh 

Steps to Reproduce:
After navigating to http://test.mapserv.utah.gov/daq/ and letting the page load.
Click on the Buffer tool, the Buffer Tool Container appears.
I click activate to turn the buffer on, just using the default 5000 meters for the buffer size.
However even though the tool has been activated, no buffer appears, so I am unable to apply the buffer.

![Uploading image.png…]()

**Comment by steveoh** [comment]
I think we may need to add a layer select to know which layer to apply the buffer to but the real problem is a missing file

![image](https://cloud.githubusercontent.com/assets/325813/23468073/0fb2133c-fe5d-11e6-8159-2b89840ae18e.png)

**Comment by woswald** [comment]
The buffer tool seems to not be working again:

Steps to Reproduce:
After navigating to http://test.mapserv.utah.gov/daq/ and letting the page load.
Click on the Buffer tool, the Buffer Tool Container appears.
I click activate to turn the buffer on, just using the default 5000 meters for the buffer size.
However even though the tool has been activated, no buffer appears, so I am unable to apply the buffer.
