### ISSUE TITLE
EDocs View Incorrect

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#30]
Access to the document view with EDocs using a particular AI# seems for be persisting from one point to another, instead of refreshing for each point.

### Steps to reproduce
1. Click on a facilities point.
2. See that it has an AI #.
3. Click on the EDoc Items tab to see documents associated with that AI#.
4. Finish with that point.
5. Click on new facilities point.
6. See that it does not have an AI#.
7. Click on the Edoc Items tab, even though no the point has no associated AI#, documents are shown.  These documents seem to be associated with prior point.

### Expected behaviour
If no AI# is associated with a facilities point, you should not be able to see any documents in the Edoc Items tab. An AI# should be required to be entered first, before any documents would appear. Documents from one point should not persist for future points.

### Actual behaviour
Even for points without an AI#, documents from prior points are shown in their EDoc Items tab.

### Client configuration
Chrome Version 56.0.2924.87

**Operating system:**
Windows 7
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
![noai](https://cloud.githubusercontent.com/assets/7386943/23472098/00a488b4-fe69-11e6-93d1-54599288cb27.png)
![edocs lingering](https://cloud.githubusercontent.com/assets/7386943/23472101/02bf0322-fe69-11e6-9e42-c50f6dce4bbc.png)

**Comment by steveoh** [comment]
The Edocs tab should only display when the layer has an `AI_Number` field and the `AI_Number` is not empty.
