### ISSUE TITLE
External File Tool Reset

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#35]
**Steps to reproduce**

1 )Navigate to http://test.mapserv.utah.gov/daq/
2) Click on a facilities point.
3) Click on EDoc Items tab.
4) Click Choose File next to External File.
5) Choose a PDF file from computer to attach. Select the file and click open.
6) Click attach.
7) The attach button becomes a success button once the attachment has been made.
8) Now I am ready to attach another file. However, the External File attachment tool doesn't reset.

**Expected behaviour**

Should be able to attach a file to a point using the external file attachment tool. After I get a success message when the file gets attached, the external file tool should then reset.  I should then be able to see in somewhere in the window the document I already attached, but should also then be able to use the reset external file tool to attach a new document.

Being able to see what files have been attached will make it easy for users when they may be attaching several external files.

**Actual behaviour**

After a successful file attachment with the External File tool, the success message persists, and the tool is not reset. The attached document is not shown in the window, the name just persists in the field browser until a new file is selected.

**Client configuration**

Chrome Version 56.0.2924.87

**Operating system:**
Windows 7

**Comment by steveoh** [comment]
I will remove your comment from https://github.com/agrc/daq-web-framework/issues/6 since they seem to overlap but with different upload items. Please correct me if I am wrong.

**Comment by woswald** [comment]
You are correct, sorry about the duplication.
