### ISSUE TITLE
Add Symbols

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#37]
### Steps to reproduce
1. After the map has loaded.
2. Click on the map layers tool icon at the bottom of the screen.
3. The name of each of the 4 layers is displayed in the tool container.

Request:
Would it be possible that in addition to the name of each layer, we also add a legend to this tool?  So each layer name would also show the symbol related to that layer. This will allow users to know how each layer is represented on the map.

**Comment by steveoh** [comment]
I should be able to do this. some notes for myself...

1. check how the layer is [styled](https://developers.arcgis.com/javascript/3/jsapi/featurelayer-amd.html#styling) 
1. Get the symbol from the graphics or the [renderer](https://developers.arcgis.com/javascript/3/jsapi/renderer-amd.html) from the [feature layer](https://developers.arcgis.com/javascript/3/jsapi/featurelayer-amd.html#renderer).
1. insert next to layer list with [getshapedescriptors](https://developers.arcgis.com/javascript/3/jsapi/esri.symbols.jsonutils-amd.html#getshapedescriptors)

**Comment by woswald** [comment]
**Steps to reproduce**
1. After the map has loaded.
2. Click on the toggle visible layers tool icon at the bottom of the screen.
3. The name of each of the 4 layers is displayed in the tool container.
4. Click on the drop-down arrow next to one od the layers.
5. No layer symbol gets displayed.

**Expected Result**
1. After the map has loaded.
2. Click on the toggle visible layers tool icon at the bottom of the screen.
3. The name of each of the 4 layers is displayed in the tool container.
4. Click on the drop-down arrow next to one of the layers.
5. The layer symbol gets displayed next to or under the layer name.
![image](https://cloud.githubusercontent.com/assets/7386943/24124858/449cb088-0d8b-11e7-8e85-fa7e9a706cfb.png)

**Comment by steveoh** [comment]
Thank you for this. this is working in dev so I will investigate the difference in stage.

**Comment by steveoh** [comment]
version 1.5.2 has fixed this issue. thanks for reporting this.
