### ISSUE TITLE
add geographic subqueries to the query

### ISSUE THREAD

**Issue by steveoh** [agrc/daq-web-framework#40]
Update current Select Items with Query with Spatial Restriction

Desired Flow: 
1. choose layer
1. choose query
1. choose spatial restriction
   - options: Statewide, County, User drawn Rectangle.

**Comment by steveoh** [comment]
@woswald what do you want the `geographic areas` to be for this?

**Comment by woswald** [comment]
@steveoh 
I was thinking that maybe there would be the option to select an individual county, statewide, or draw a shape. I thought it might be similar to how the interactive map works (http://enviro.deq.utah.gov/).
![image](https://cloud.githubusercontent.com/assets/7386943/24224064/c9ca880e-0f1e-11e7-928d-de7113c44a5e.png)

Let me know if I need to try and explain better.

**Comment by steveoh** [comment]
ok duplicating that functionality will require some time.
