### ISSUE TITLE
Accessible Images

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#43]
Current:
In Collector, users are able to attach images to specific points included in the "2014 O&G Facilities" layer.  Currently, the only way for a user to view these images after making the attachment is either through the Collector application or logging into ArcGIS Online.  

Desired:
One of our goals with the Compliance tablet application was to keep things simple for users and not require them to have to see the complicated interface of AGOL.  I am wondering if we can somehow bypass the need for users to go to AGOL to view images by instead making them available in the attribute tables shown in the Compliance tablet app (http://test.mapserv.utah.gov/daq/).  This would enable users to easily access images they took in the field from their dektop when they get back into the office without having to navigate through AGOL.  This would alllow them to easily download and attach these images to the compliance memos they write when returning to the office.

**Comment by steveoh** [comment]
sounds like a good idea.

**Comment by woswald** [comment]
Can this be done for all 3 layers?

**Comment by brigsz** [comment]
Wheeeeeeew!  do you want fries with that?

**Comment by woswald** [comment]
I know right.  This is what happens when I start writing the manual for this stuff.  I start realizing all the thing I didn't think about and start making crazy demands. :)

**Comment by brigsz** [comment]
It is good to get these ideas out now though.  @steveoh can you give us some general hour estimate such as +10 or -20  etc
