### ISSUE TITLE
Increase Document Attachment Size to 20mb

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#48]
### Steps to reproduce
1. Open http://test.mapserv.utah.gov/daq/ and wait for it to load.
2. Navigate to POI using query search (any point with the EDoc Items tab should work)
3. Click on POI, click to open EDoc Items tab.
4. Click the "Choose File" button to attach an External File.
5. Select a file from the popup window to attach, click the "Open" button.
6. Click the "attach" button.
7. Receive an error (see image) saying "RequestError: Unable to load/daq/upload/external status:404".
**Note:** This error seems to be related to file size, I think files larger than 10 mb are not able to be attached. 

![image](https://user-images.githubusercontent.com/7386943/27549254-a06ff3d8-5a58-11e7-9e4f-441eb4b278e7.png)

Can we increase the attachment file size limit to maybe 20mb? It looks like we had a few permit documents around 15mb.

### Expected behaviour
1. Open http://test.mapserv.utah.gov/daq/ and wait for it to load.
2. Navigate to POI using query search (any point with the EDoc Items tab should work)
3. Click on POI, click to open EDoc Items tab.
4. Click the "Choose File" button to attach an External File.
5. Select a file from the popup window to attach, click the "Open" button.
6. Click the "attach" button.
7."file saved successfully!" message is received, and document is attached to POI.

### Actual behaviour
Receive an error (see image) saying "RequestError: Unable to load/daq/upload/external status:404".
**Note:** This error seems to be related to file size, I think files larger than 10 mb are not able to be attached. 

### Client configuration
Chrome, IE

**Operating system:**
Various (Windows XP, Windows 7, and Mac Sierra 10.12)

**Comment by woswald** [comment]
I tried attaching a 13.693 mb file (See attached).  I received the following error.

![image](https://user-images.githubusercontent.com/7386943/28172694-7f94a24a-67a9-11e7-9343-8899256d194c.png)

[air_pollution_prevention_control_handbook.pdf](https://github.com/agrc/daq-web-framework/files/1145615/air_pollution_prevention_control_handbook.pdf)

**Comment by steveoh** [comment]
That is an error coming out of arcgis online. Is there a setting you can manipulate from your organization? The error code is 413.

**Comment by woswald** [comment]
I don't know.  
I Googled and found this: http://doc.arcgis.com/en/arcgis-online/share-maps/manage-hosted-feature-layers.htm 
The "Allow Attachments" section might be helpful.

**Comment by steveoh** [comment]
```
Each file you attach to a feature can be a maximum size of 10 MB. To attach files larger than 10 MB, you can use the Upload Part and Add Attachment operations from ArcGIS REST API to do a multipart upload.
```

I am already using the `addAttachment` endpoint.
`arcgis/rest/services/2015_OGFacilities/FeatureServer/0/371/addAttachment`

I can't find another one on the feature service itself.
