### ISSUE TITLE
Point Highlight Adjustment

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#49]
When selecting a POI with a query or when hovering over a result returned in the buffer results table, a lime green circle is used to highlight the point.  On a large monitor (like what I used for testing) the highlighted point is easy to see.  However, after we completed in office/in field training with compliance inspectors, it was pointed out that the highlighted point is difficult to see.  Also if the point selected is located on a layer below another layer it gets hidden under the upper layers (e.g. if the selected point is in the "Permits" layer, when it is selected it gets hidden by the higher layers, the facility and wells layers).  Is there any way we can increase the size of the symbol used to represent the selected point?

**Comment by steveoh** [comment]
Yes, I will make it larger and easier to see.
