### ISSUE TITLE
PDF attachment does is unable to open

### ISSUE THREAD

**Issue by steveoh** [agrc/daq-web-framework#5]
1. add pdf
1. open attributes
1. download attachment
1. collector says no app found when acrobat etc are available

**Comment by woswald** [comment]
The same pdf added through ArcGIS.com works fine 
1. add pdf in arcgis.com
2. open attribute in collector
3. download attachment (shows up as red not greyed out - see attached image).
4. click on attachment again and it opens
![screenshot_2017-02-02-12-27-41](https://cloud.githubusercontent.com/assets/7386943/22564863/4c17f3b6-e943-11e6-93ef-50fd0d6d1a4d.png)

**Comment by steveoh** [comment]
Ok. My guess at the moment is with [this header value](https://github.com/agrc/daq-web-framework/blob/28b131cbf40f45950774e129d711eefda5295191/api/Modules/UploadModule.cs#L43). I think maybe it should be `application/pdf` based on [this thread](http://stackoverflow.com/questions/312230/proper-mime-media-type-for-pdf-files)

**Comment by steveoh** [comment]
I tested this on Collector for iOS and it worked. Can you please test on android and leave a comment.
