### ISSUE TITLE
EDocs Error?

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#50]
This error may not be an issue with the application it may be an issue with EDocs itself, or it may be a result of still being on the test server (and EDocs not being fully connected yet), that is what I am trying to determine. 

### Steps to reproduce
1) Open http://test.mapserv.utah.gov/daq/ and wait for it to load.
2) Navigate to POI using query search (any point with the EDoc Items tab should work)
3) Click on POI, click to open EDoc Items tab.
4) Determine an EDocs document you want to attach, click the "add" button next to the document to attach the document.
5) Receive an error (see image) saying "Unkown error getting EDocs File. Could not find a part of the path ......".

![image](https://user-images.githubusercontent.com/7386943/27550786-337f010a-5a5e-11e7-9451-922f9b50e5fc.png)

### Expected behaviour
After steps 1-4, should receive a processing notification, add button should then change from "add" to "remove".

**Comment by steveoh** [comment]
I would assume that that doc is not on the edocs test server. I would ask your support folks to verify but for the time being I think that is safe to assume.
