### ISSUE TITLE
Planned POI List

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#51]
**Request**
After using the Desktop application to determine the sites you want to visit, it is necessary to keep a written list of the sites and their coordinates so that you can search for them again later on the tablet with Collector.  If you forgot to list a site or messed up writing down the site coordinates it is nearly impossible on the tablet to search for and find the specific site.  Is there any way to provide a layer, with just the sites a user determines, to Collector?  Or is there really any better, less onerous, way we could enable users to better track the sites they identified on the desktop side of the app, and have those available via the tablet?  

Per Steve's suggestion can we utilize the bookmarks function to accomplish this?

**Desired Functionality**
1) Using the Desktop application (test.mapserv.utah.gov/daq/), locate a POI you are interested in visiting while in the field and want to be able to access information for from your tablet (Collector). 
2) Zoom in on the POI, enough so that other points are not included in the same view.
3) Click on the bookmark tool, the tool will open in the tool container.
4) Would like the user to be able to have access to a button to save the current extent/view as a new bookmark, and also name the bookmark.
5) After a bookmark has been added, would like the user to be able to drag any of the bookmarks into a new order.
6) It would also be nice to have the ability to edit and delete each bookmark.
7) Finally, if there is any way to keep these types of bookmark somewhat separate from the county and state ones already included in the app. that would be helpful.  This might keep things from getting too crowded and confusing when trying to navigate with the existing bookmarks.  This Step is not a must-have but more of a nice-to-have.
8) When using the tablet application Collector, all of the bookmarks created with the Desktop application would be accessible.  A user can then use these bookmarks to remember the sites they are visiting that day.  They will be able to easily navigate to each of these sites in Collector just by clicking the applicable bookmark rather than having to remember lat/long coordinates for each site, and then searching with theses coordinates in Collector.

**Comment by steveoh** [comment]
@woswald The app is having issues saving bookmarks. Would you check on permissions and sharing settings of the web map and the application account item.

**Comment by woswald** [comment]
@steveoh Give it a try now.

**Comment by steveoh** [comment]
AGOL continues to return `{success: false}`. 

As a side note, In my dev environment, the webmap is popping this dialog box:

![image](https://user-images.githubusercontent.com/325813/28329738-1fb238f8-6ba8-11e7-9195-e53e76250550.png)

It is not doing that in test even though both sites are using the same credentials. I did update the esri js version in dev. I will try to downgrade it and see what happens.

**Comment by woswald** [comment]
I will double check the permissions again.

**Comment by woswald** [comment]
I double checked the permissions on my end, and as far as I can tell the permissions look the same between prod and test.  Do you want me to assign ownership to you again?

**Comment by steveoh** [comment]
@woswald Can you get setup with a mic or a phone call and a machine where you can share your screen for a hangout. I'd like to walk through some ago-assisant.esri.com through your account and see if you have permission.

**Comment by woswald** [comment]
@steveoh Sure send me a hangout link and I'll join in.

**Comment by steveoh** [comment]
@woswald can you read [this page](http://doc.arcgis.com/en/arcgis-online/share-maps/create-groups.htm#ESRI_SECTION1_946848D9B81D4607B3E3AB706EB267E3) around this note

> Choosing All items (group membership is limited to the organization) enables the item update capability on the group. Only members with level 2 accounts in the same organization can belong to a group with this capability enabled, and these members can update the items regardless of their privileges. However, they cannot perform other actions that are outside their privileges. For example, if they do not have privileges to create content, they cannot save a copy of a map they update. Only the owner (or administrator) of the item can perform the following actions on the item (not all actions apply to all item types): delete, share, move, change owner, change delete protection, publish, register an app, overwrite data in hosted feature layers, and manage tiles in hosted tile layers.

and check if the group has item update capabilities?

**Comment by steveoh** [comment]
from [this doc](https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/limitations-of-application-authentication/)

> Applications cannot create, update, share, modify, or delete items (layers, files, services, maps) in ArcGIS Online or Portal for ArcGIS.

We might be barking at the wrong tree.

**Comment by steveoh** [comment]
Or we could switch to using a named user and not use the oauth app to get the token to take care of this. That would take up a named user account.

**Comment by woswald** [comment]
@steveoh Would it just take up one user account?

**Comment by steveoh** [comment]
yes

**Comment by steveoh** [comment]
We should try the item update setting on the group though. Were you able to update that?

**Comment by woswald** [comment]
I think that would be fine, we still have a user account left over from the STEPP project we completed a few months ago.  Do you want the user info for that account?

**Comment by steveoh** [comment]
Thank you for the user account information @woswald. Unfortunately agol is continuing to return 

`You do not have permissions to access this resource or perform this operation`

Did you update the permissions on the resources the app uses for the user that you sent me info for?

**Comment by woswald** [comment]
@steveoh I just updated that account to a publisher account. Let me know if that helps.

**Comment by steveoh** [comment]
@woswald Yes I believe that allowed me to save the bookmarks but now the app cannot load the webmap. You can see what I'm talking about in the website in test.

**Comment by steveoh** [comment]
I think I might still need to use the daq app login for this token. Let me try that. Did you remove that item or remove it's permissions by chance?

**Comment by woswald** [comment]
No, I didn;t change anything.  I also just logged into AGOL with the STEPP1 account and I can see the webmap and all the other content shared with the "Oil and Gas Compliance App Development - TEST" group there.  So access via AGOL seems fine, I'm not sure why it would be different in the app.

**Comment by steveoh** [comment]
I might have corrupted the web map json since I can't view the web map properly in arcgis online.

**Comment by woswald** [comment]
I see what you mean.  I can't open "2015 Oil and Gas Compliance Map" in AGOL either.  I can still see 2015 "Oil and Gas Compliance Map-PROD".

**Comment by steveoh** [comment]
Are we still using separate maps for collector and the web app? If that is the case then I do not think the bookmarks will be synced to collector. Let me know how that piece is working and I might need to update the web map json of two web maps for this to function as expected.

**Comment by woswald** [comment]
I think we were only doing that because the imagery was showing up strangely in Collector.  I would be happy if we could get rid of the two separate maps and find a way for the map and imagery to work in Collector.  Let me know if there is anything I need to do.

**Comment by woswald** [comment]
@steveoh 
The bookmarks tool works great on https://test.mapserv.utah.gov/daq/. However, I am unable to see any of the new bookmarks in Collector.  

Additionally, the imagery is showing up strangely in Collector as well if I use the PROD map rather than the Collector specific map (See image).  I also can't open "2015 Oil and Gas Compliance Map" in Collector.
![screenshot_2017-07-31-11-15-38](https://user-images.githubusercontent.com/7386943/28789997-abed1608-75e4-11e7-9131-be4cd39dfb9c.png)

**Comment by steveoh** [comment]
Yeah, we cache the western states since our base maps are rarely overlaid on top of other imagery products. And since we don't do global mapping we only do that chunk. So if you don't like the way that looks in collector we will have to stick with multiple web maps. I can store the bookmarks in both web maps. I will also look into why that map doesn't open in collector. Are you able to open it in online? Send me the link so I don't have to search around for the specific web map. Thanks.

**Comment by woswald** [comment]
Here is the link for 2015 Oil and Gas Compliance Map, I can open it in AGOL but not Collector. 
 https://utahdeq.maps.arcgis.com/home/webmap/viewer.html?webmap=54525aa512544213adf194303769b643

The problem is as much with the way it looks in Collector, it does look strange, but that isn't the biggest deal.  The bigger deal is that it seems to place the imagery for Utah in a weird way in the map in Collector.  If you looks at the picture I posted above, you can see that the white overlay is place too far south on the map, so that Utah almost ends up where Arizona should be,  then because of this the real time location idicator on the map shows the location in Idaho instead of in Utah.  Also all the data maps to the lower imagery layer rather than the one visible on top. Is there anyway to fix this other than multiple web maps?

I think storing bookmarks works fine for me also, it's just viewing them in Collector that I am unable to do.  Only the main bookmarks (the county ones and Utah) show up.

**Comment by steveoh** [comment]
I published 1.10.1 to update the collector web maps with bookmarks so they are in sync with each other. The collector and discover alignment might be an esri trouble ticket. I can look into it or you can. Let me know.

**Comment by woswald** [comment]
If you could talk to Esri that would be great. I am worried I wouldn't have enough info about how the bookmarks functionality is currently set up.  I am also happy to do a conference call if needed.

**Comment by steveoh** [comment]
We need to talk to esri about the map not aligning. The bookmarks are fine.

**Comment by woswald** [comment]
@steveoh I am not able to create new bookmarks using https://complianceapp.utah.gov/

After zooming to a point of interest and entering data in the "For" and "Bookmark Name" fields, and then clicking save, I get a red/white crossed out icon for my cursor, but then nothing happens, no bookmark is ever created.

**Comment by steveoh** [comment]
Ok. The link for the adding endpoint is wrong in production. I'll assume all the api endpoints are also broken.
