### ISSUE TITLE
Issue with EDoc Items Tab

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#55]
### Steps to reproduce
1. Load https://test.mapserv.utah.gov/daq/
2. Click on a point with an AI #.
3. Click on the EDoc Items Tab heading to open the tab.
4. I receive an error see image. I am not able to access any of the document attachment tools.

![image](https://user-images.githubusercontent.com/7386943/28130175-48bac4ae-66f3-11e7-9dfd-bc0b745deb4c.png)

**Comment by steveoh** [comment]
I think this was caused by the #56
