### ISSUE TITLE
Attachment Issue

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#58]
@steveoh 
One of the compliance inspectors gave the following error with complianceapp.utah.gov:

I tried to attach the AO from the eDoc Items tab
I clicked the Add button, and received the following error
![image](https://user-images.githubusercontent.com/7386943/32279305-fd7a319e-bedd-11e7-8fd5-f611b4276c37.png)

The Word file is only 145 KB, so I imagine the PDF isn't more than half a MB 
I was able to attach the Word document by uploading from my computer

**Comment by woswald** [comment]
This is specifically for the permitted facility with AI# 14819.  There is only one item showing from edocs, so that should be the doc they were trying to upload.  I can't see any size info about the file, so I am not 100% sure how large it is.

![image](https://user-images.githubusercontent.com/7386943/32281264-f37b95c4-bee3-11e7-9f71-a436615c7d09.png)

**Comment by woswald** [comment]
I was able to get a hold of the doc from EDocs and it looks like it is well over the 10 mb upload limit (17.3mb).  That is our size cutoff right?

**Comment by steveoh** [comment]
yup
