### ISSUE TITLE
Query Issue

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#59]
@steveoh
One of the compliance inspectors gave me the following error with complianceapp.utah.gov:

I was in the Permits layer.
I queried Ai numbers
My input was 14819
I restricted the query to Duchesne County
I got the following error
![image](https://user-images.githubusercontent.com/7386943/32279451-691d5f20-bede-11e7-8d0f-2bd61ab380f8.png)

I am wondering if this has anything to do with creating new layers, maybe I wasn't able to get the naming exact.  Is this something you can check on your end?

**Comment by steveoh** [comment]
Can you verify that the attributes for the layers are matching with [this config file](https://github.com/agrc/daq-web-framework/blob/master/src/app/config.js#L28-L79)

**Comment by woswald** [comment]
**For Facility**
On line 61, the field should now be 'InspInit' rather than:
 
inspector: {
                    field: 'Inspector',
                    type: 'string'

**For Permit**
On line 71, the field should now be 'AI_Number' rather than:

aiNumber: {
                    field: 'SITE_ID',
                    type: 'number'

**Comment by steveoh** [comment]
Are there any changes to [these fields](https://github.com/agrc/daq-web-framework/blob/master/src/app/config.js#L21-L27) as well? I think I can remove `SITE_ID` from permits since you changed that to `AI_NUMBER`.

**Comment by woswald** [comment]
It looks like SITE_ID is the only one.

**Comment by steveoh** [comment]
try this with 1.10.3 and let me know how it goes.

**Comment by woswald** [comment]
Works great! Thanks!
