### ISSUE TITLE
Files already added 

### ISSUE THREAD

**Issue by steveoh** [agrc/daq-web-framework#6]
When an item is added from the table of edoc items and then closed and reopened the UI does not show that the file has already been added. Figure out a way to make that work.

**Comment by woswald** [comment]
Is there any way to do something similar with the files added via the External File tool too.  Some way to know which files have been attached, at least while in the session, would be very helpful.

**Comment by woswald** [comment]
I am unable to test "File uploads are now synced from arcgis online and the edoc grid".  For any facility point that I click on with an AI#, when I click on the EDoc Items tab I receive the following error: 
![image](https://cloud.githubusercontent.com/assets/7386943/24002353/1f97b476-0a26-11e7-9032-113da1c0c21c.png)

I was unable to find any facility points with an AI# where this didn't occur.

**Comment by steveoh** [comment]
Clear your cache. Your version is still at 1.4.3
