### ISSUE TITLE
Rename Attachment Filenames

### ISSUE THREAD

**Issue by steveoh** [agrc/daq-web-framework#7]
rename attachments to something like `facilityid` + substring(0, n) with punctuation removed + `title`

This should help with #6

**Comment by woswald** [comment]
@steveoh 

I am having a hard time testing this. I can't seem to find a facility that has attachable document via EDocs in http://test.mapserv.utah.gov/daq/, I know that the testing file server does not contain all of the documents.  Is there are a particular point that you know of that will work?

**Comment by steveoh** [comment]
The AI# `10791` is the one I use that I know has documents.

**Comment by woswald** [comment]
I attempted to use 10791 as the AI# for a point, but I am unable to make a document attachment (see Issue #32) for any EDoc document.
